#![no_std]
#![allow(unused_imports)]

extern crate alloc;

// Where prost puts the messages and the bindings: one module per package.
#[allow(clippy::all)]
pub mod fixture {
    pub mod api {
        include!(concat!(env!("OUT_DIR"), "/fixture.api.rs"));
    }
    pub mod other {
        include!(concat!(env!("OUT_DIR"), "/fixture.other.rs"));
    }
}

// A keyword module override, generated by a directly configured generator.
#[allow(clippy::all)]
pub mod escaped {
    include!(concat!(env!("OUT_DIR"), "/escaped/escaped.rs"));
}

pub const ESCAPED_SERVICE: &str = escaped::r#type::SERVICE_NAME;

use fixture::api::{Common, Reply, Request, request::Inner};

#[cfg(feature = "server")]
pub fn servers() {
    use protolink_grpc::{CallContext, Handler, Status};

    struct Echo;
    impl fixture::api::echo_grpc::Echo for Echo {
        fn unary(&mut self, _: &mut CallContext<'_>, request: Request) -> Result<Reply, Status> {
            Ok(Reply {
                inner: request.inner,
            })
        }
        fn nested(&mut self, _: &mut CallContext<'_>, request: Inner) -> Result<Reply, Status> {
            Ok(Reply {
                inner: Some(request),
            })
        }
        fn remote(
            &mut self,
            _: &mut CallContext<'_>,
            _: fixture::other::Remote,
        ) -> Result<prost_types::Timestamp, Status> {
            Ok(prost_types::Timestamp::default())
        }
    }
    struct Match;
    impl fixture::api::match_grpc::Match for Match {
        fn r#type(&mut self, _: &mut CallContext<'_>, request: Request) -> Result<Reply, Status> {
            Ok(Reply {
                inner: request.inner,
            })
        }
        fn r#async(&mut self, _: &mut CallContext<'_>, request: Common) -> Result<Common, Status> {
            Ok(request)
        }
    }
    struct Second;
    impl fixture::api::second_grpc::Second for Second {
        fn ping(&mut self, _: &mut CallContext<'_>, request: Common) -> Result<Common, Status> {
            Ok(request)
        }
    }
    fn handler(_: impl Handler) {}
    handler(fixture::api::echo_grpc::EchoServer::new(Echo));
    handler(fixture::api::match_grpc::MatchServer::new(Match));
    handler(fixture::api::second_grpc::SecondServer::new(Second));
}

#[cfg(feature = "async-client")]
pub async fn async_clients<T>(transport: T)
where
    T: protolink_grpc::UnaryTransport + protolink_grpc::StreamingTransport,
{
    let mut client = fixture::api::echo_grpc::EchoClient::new(transport);
    let _ = client.unary(&Request::default()).await;
    let _ = client.remote(&fixture::other::Remote::default()).await;
    if let Ok(mut stream) = client.fan(&Request::default()).await {
        let _ = stream.message().await;
    }
    if let Ok(upload) = client.collect().await {
        let _ = upload.finish().await;
    }
    if let Ok(mut chat) = client.chat().await {
        let _ = chat.send(&Request::default()).await;
        let _ = chat.close_send().await;
        let _ = chat.message().await;
    }
}

#[cfg(feature = "blocking-client")]
pub fn blocking_clients<T>(transport: T)
where
    T: protolink_grpc::BlockingUnaryTransport + protolink_grpc::BlockingStreamingTransport,
{
    let mut client = fixture::api::echo_grpc::EchoBlockingClient::new(transport);
    let _ = client.unary(&Request::default());
    if let Ok(mut stream) = client.fan(&Request::default()) {
        let _ = stream.message();
    }
    if let Ok(upload) = client.collect() {
        let _ = upload.finish();
    }
    if let Ok(mut chat) = client.chat() {
        let _ = chat.send(&Request::default());
        let _ = chat.close_send();
        let _ = chat.message();
    }
}
